FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository -y ppa:bitcoin-abc/ppa
RUN apt-get update
RUN apt-get install -y bitcoind

EXPOSE 8332 8333 28332

CMD ["bitcoind"]
